### PR TITLE
feat: add type checking for strict converterOptions

### PR DESCRIPTION
**Pull request by srabouin**
I did not have a use case for the rounding option, so I am not sure what example could be made with it, but added it just in case someone wants to use it :D

### CODE REVIEW

**Comment by srabouin** [comment]
lint always killing me, sorry ;(

**Comment by MrDeerly** [comment]
Hey @srabouin,

thanks for the PR! 

I was also thinking about adding this to the initial commit. I didn't do it because it could cause confusion about the available options. We probably should've went with another converter instead of adding the functionality to the default converter. Give me a few days to think about a possible solution for it. 

And now worries about the linitng :)

**Comment by MrDeerly** [comment]
@srabouin Can you please take a look at my propsed changes in https://github.com/MrDeerly/vue-timeago3/pull/262/commits/5233f764dbcc83cf2027b1a53a45ce7e361003a5 and share your thoughts with me? :) If it fits we just need to adjust the docs so the "dynamic" options are clear for users.

**Comment by srabouin** [comment]
Few days in 1 hour 🤣 

Looks fine to me, it does add a bit of clarity. 👍

**Comment by MrDeerly** [comment]
> Few days in 1 hour 🤣
> 
> Looks fine to me, it does add a bit of clarity. 👍

hahah time flies 😂 

Great! I'll adjust the docs a little tomorrow (or in another hour lol). If you get bored, feel free to do so :P

**Comment by MrDeerly** [comment]
Sorry, that took a bit longer -.- I adjusted the docs a bit and will release it in a few. Thanks alot for your contribution! :)

**Pull request merged**
